### PR TITLE
Add ASAP as acronym

### PR DESCRIPTION
**Pull request by eliazonta**
(this is my first contribution) I added "ASAP" as acronym and I fixed some capital letters missing in the "Usage" column

(any tip is welcome)

### CODE REVIEW

**Comment by aloisdg** [comment]
Thank you for contributing. You edited the generated file. Can you move your contribution to [acronyms.json](https://github.com/d-edge/foss-acronyms/blob/main/data/acronyms.json)?

Thank you

**Comment by eliazonta** [comment]
I should have done it rn, if there are problems tell me (sorry but these are my first contributions so I don't know how to do them properly)

**Comment by aloisdg** [comment]
@eliazonta no problem take your time. You are doing well. You closed this merge request which is fine but you could have edit it too. If you want more help feel free to ask and I will gladly help :)

**Comment by eliazonta** [comment]
thank you for being patient with me, I created a new pull request with the correct version because searching online seems that I can't edit the previous one because involves a different file (am I wrong?)

**Comment by aloisdg** [comment]
Well you should be able to edit it as well. Try this [link](https://github.com/eliazonta/foss-acronyms/edit/patch-1/README.md?pr=%2Fd-edge%2Ffoss-acronyms%2Fpull%2F38) to rollback the edited file. You will have to create a new commit.

Then edit the data/acronyms.json with this [link](https://github.com/eliazonta/foss-acronyms/edit/patch-1/data/acronyms.json?pr=%2Fd-edge%2Ffoss-acronyms%2Fpull%2F38)

**Comment by eliazonta** [comment]
Thank you another time for explaining me, hopefully I have done it correctly (if so I will close the other pull request that I made) tysm :) !!

**Comment by eliazonta** [comment]
ok I think I fixed that thing now, thank you for letting me learn this things!
if I didn't got it wrong the readme file is created (and updated) by the /.github/workflows/markdown-from-json.yml ?? am I wrong? 
and then you want me to create the TYSM thing here in this pull request or creating another one ? 
because it seems I can't create another one (?)

**Comment by aloisdg** [comment]
> ok I think I fixed that thing now, thank you for letting me learn this things

And thank you for contributing to improve this project!

> if I didn't got it wrong the readme file is created (and updated) by the /.github/workflows/markdown-from-json.yml ?? am I wrong?

You are right. The readme's table is generated by the GitHub Action :)

> and then you want me to create the TYSM thing here in this pull request or creating another one ?
because it seems I can't create another one (?)

Creating another one would be better. We try to keep thing separated.

**Review by aloisdg — APPROVED** [review]
ACK

**Pull request merged**
