### PR TITLE
Update stacks.json with LAMP's examples

### PR DESCRIPTION
**Pull request by Amplifi-Beats**
LAMP examples added

## If you want to add or update an acronym

Keep in mind that the [readme.md] is generated. It is useless to edit it directly.
If you want to add or update an acronym, edit the correct file in the [data] folder
(e.g. [acronyms.json])

## Checklist before merging

- [x] The title says what this PR do
- [x] The description includes an issue ticket number if any
- [x] Only a `json` is changed if you want to add or update an acronym

[readme.md]: https://github.com/d-edge/foss-acronyms/blob/main/README.md
[data]: https://github.com/d-edge/foss-acronyms/tree/main/data
[acronyms.json]: https://github.com/d-edge/foss-acronyms/blob/main/data/acronyms.json

### CODE REVIEW

**Review by aloisdg — APPROVED** [review]
Good to go!

**Comment by Amplifi-Beats** [comment]
thanks! should I have edited the comment that came with this pull request? I left it as is as I wasn't sure

**Comment by aloisdg** [comment]
It's good. Feel free to improve it later on if you want to

**Comment by Amplifi-Beats** [comment]
yes, will do! ty

**Pull request merged**
