### PR TITLE
Add companies and orgs

### PR DESCRIPTION
**Pull request by boehs**

### CODE REVIEW

**Comment by boehs** [comment]
I think perhaps what each org does would be useful

**Comment by aloisdg** [comment]
Hi!

+1 for the meaning of each group.  
Could you drop the M$? MS is enough.
Good job. :)

**Comment by aloisdg** [comment]
The markdown table doesn't seems to work. Here is what I saw on GH: https://github.com/d-edge/foss-acronyms/pull/8/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by boehs** [comment]
Good catch

**Comment by aloisdg** [comment]
You can fix it by adding a dash `|-|-|-|-`

**Comment by aloisdg** [comment]
it works! Now I have a question, should GNU move to the main table? It is not a company, nor an organization nor quite a community. It is a collection of software as you said.

**Comment by boehs** [comment]
I don't think so, I personally look at GNU as a collective, they have a website, a foundation, and (a project?)

**Comment by aloisdg** [comment]
Alright. We will keep it here and see if someone mention it.

**Review by aloisdg — APPROVED** [review]

**Pull request merged**
