### PR TITLE
KISS acronym

### PR DESCRIPTION
**Pull request by iamrahulrnair**
Add **KISS** description

### CODE REVIEW

**Comment by aloisdg** [comment]
Hi again!

Can you move one of the two whitespaces before the `|[Wikipedia]` to have

`KISS is a design principle stating that most systems work fine if it is built/kept simple than making the system complex. | [Wikipedia](https://en.wikipedia.org/wiki/KISS_principle#:~:text=KISS%2C%20an%20acronym%20for%20keep,unnecessary%20complexity%20should%20be%20avoided.` instead of `KISS is a design principle stating that most systems work fine if it is built/kept simple than making the system complex.  |[Wikipedia](https://en.wikipedia.org/wiki/KISS_principle#:~:text=KISS%2C%20an%20acronym%20for%20keep,unnecessary%20complexity%20should%20be%20avoided.`

**Comment by iamrahulrnair** [comment]
> Hi again!
> 
> Can you move one of the two whitespaces before the `|[Wikipedia]` to have `the system complex. | [Wikipedia` instead of `system complex. |[Wikipedia`.

Removed whitespace, thanks for notifying 😉

**Review by aloisdg — APPROVED** [review]

**Comment by aloisdg** [comment]
You are welcome :)

**Comment by aloisdg** [comment]
Thank yo for your work

**Comment by iamrahulrnair** [comment]
> Thank yo for your work

I am new to open source and still exploring, will be adding more descriptions for acronyms soon , thanks 😄

**Pull request merged**
