### PR TITLE
Add RTFM definition

### PR DESCRIPTION
**Pull request by mcanever**
First contrib here! :tada:
A slightly censored definition of RTFM.
GO D-Edge open source! :rocket:

### CODE REVIEW

**Comment by aloisdg** [comment]
Could you write "Read The F***ing Manual" instead. The strike trough is just a design element and we may not want to have the word linked to D-EDGE

**Comment by mcanever** [comment]
@aloisdg done! Had to forcepush twice as my tools were adding unnecessary whitespace to the commit

**Comment by aloisdg** [comment]
Let's merge that :)

**Review by aloisdg — COMMENTED** [review]
Merged

**Pull request merged**
