### PR TITLE
DRY Acronym

### PR DESCRIPTION
**Pull request by iamrahulrnair**
Hey, I have added description for DRY in README.md, and specific resource link to get further idea behind it

### CODE REVIEW

**Review by aloisdg — COMMENTED** [review]
"resuability"=>"[reusability](https://www.thefreedictionary.com/reusability)". Use Wikipedia instead of Programming in the link.

**Comment by iamrahulrnair** [comment]
Done 🙂

**Comment by aloisdg** [comment]
Almost. You have a double 'd'. "reusabbility"=>"reusability". :)

**Comment by iamrahulrnair** [comment]
corrected that in latest commit [ac24cdd](https://github.com/d-edge/foss-acronyms/pull/19/commits/ac24cddde4cd6fc1ccf6ca5f4a23a7892c088070)

**Comment by aloisdg** [comment]
Great :+1:

**Pull request merged**
